### PR TITLE
[OPS-7292] Stick the ES CA cert in the bot image, so https requests just work.

### PR DESCRIPTION
**Pull request by cafuego**
Oh, also use a current node base image.

### CODE REVIEW

**Review by teodorescuserban — APPROVED** [review]
would elk create its own certificate and key signed by this ca?

**Review by attiks — APPROVED** [review]
Assuming you know what you're doing ;-)

**Comment by cafuego** [comment]
> would elk create its own certificate and key signed by this ca?

Yes, ELK uses keys signed by this CA. All are valid for 10 years. I hope we're using something else by the time they expire.

**Comment by cafuego** [comment]
> Assuming you know what you're doing ;-)

That's how I got this job.

**Pull request merged**
