### PR TITLE
[OPS-3397] alpine-hubot: Add twilio node dependency.

### PR DESCRIPTION
**Pull request by pjf**
HubbBot's new SMS capabilities require the Twilio node module is installed, so this should install it. :)

Note: JavaScript isn't my first language, so extra eyes to make sure I haven't booched it up would be appreciated.

### CODE REVIEW

**Comment by pjf** [comment]
Reviews from @attiks and @cafuego especially welcome! Please merge if happy with changes, as I don't have merge privileges. ❤️

**Comment by attiks** [comment]
We aren't using SMS for now, do you want to use it in the future?

**Comment by pjf** [comment]
@attiks : We sure do! [This](https://github.com/UN-OCHA/jebbbot/compare/ops_sms) is the branch will be landing in your PR-box soon. :)

See [this project](https://docs.google.com/document/d/1paPdceWnK-jjm0e1MNX-8MdJggiBwliDYaaRiNYkaA4/edit#heading=h.5p80da2mkfw0) for more info. :)

**Review by cafuego — CHANGES_REQUESTED** [review]
Can you add twilio to the hubot module metadata label in Dockerfile.tmpl? Apart from that, this change seems to cause:

```
twilio@3.5.0 node_modules/twilio
├── deprecate@1.0.0
├── scmp@0.0.3
├── rootpath@0.1.2
├── xmlbuilder@9.0.1
├── q@2.0.3 (weak-map@1.0.5, pop-iterate@1.0.1, asap@2.0.6)
├── request@2.81.0 (oauth-sign@0.8.2, forever-agent@0.6.1, aws-sign2@0.6.0, tunnel-agent@0.6.0, stringstream@0.0.5, is-typedarray@1.0.0, caseless@0.12.0, isstream@0.1.2, safe-buffer@5.1.1, json-stringify-safe@5.0.1, aws4@1.6.0, extend@3.0.1, performance-now@0.2.0, uuid@3.1.0, qs@6.4.0, combined-stream@1.0.5, mime-types@2.1.15, tough-cookie@2.3.2, form-data@2.1.4, hawk@3.1.3, http-signature@1.1.1, har-validator@4.2.1)
├── jsonwebtoken@7.4.1 (ms@2.0.0, lodash.once@4.1.1, xtend@4.0.1, jws@3.1.4, joi@6.10.1)
├── moment@2.18.1
└── lodash@4.0.0
```

... so that seems fine.

**Comment by pjf** [comment]
@cafuego:

**Comment by pjf** [comment]
@cafuego : Metadata added in 26aea46 on this branch! Double-checking I've done it correctly appreciated. :)

**Review by cafuego — APPROVED** [review]

**Pull request merged**
