### PR TITLE
[TEST] Add a lint tester for the Dockerfiles (and templates).

### PR DESCRIPTION
**Pull request by cafuego**
Soooo... I think the problem here is mostly that the linter is broken, as it errors out on "single quotes" even if there are no quotes in the file.

### CODE REVIEW

**Comment by teodorescuserban** [comment]
Great idea!

@cafuego actually I think the linter just want a non-zero-length array on ENTRYPOINT value.

If instead `ENTRYPOINT []` we put `ENTRYPOINT [""]` it pass the test.

The same goes with `CMD []` if replaced by `CMD [""]`

The errors about absolute path are solved by replacing `${VAR_NAME}` with `$VAR_NAME`, for example `WORKDIR ${SRC_DIR}` needs to change into `WORKDIR $SRC_DIR`

**Comment by teodorescuserban** [comment]
I think you already done that, @cafuego, right? Please close this PR whenever.

**Comment by cafuego** [comment]
I've not!

**Comment by teodorescuserban** [comment]
Hmh, I must have dreaming about it then. True, travis && dockerlint is not added.

**Review by teodorescuserban — APPROVED** [review]

**Pull request merged**
