### PR TITLE
add php7-wordpress image that includes wp-cli

### PR DESCRIPTION
**Pull request by teodorescuserban**

### CODE REVIEW

**Review by cafuego — CHANGES_REQUESTED** [review]
Oh, right, we couldn't make a single `php7` image because we can't load both pdo_mysql and mysqli, right? Annoy.

I think I should change the base image to include composer, and then you can use composer to install wp-cli, like I do for drush in the `php7` image currently.

**Comment by cafuego** [comment]
I've just had a go at updating the base image, and I think all we need is to add wp-cli into the `php7` image. No need to add mysql-client, which is already installed there or to remove php7-mysqli.

If mysqli is an issue, simply remove mysqli.ini from the stack and it won't get loaded.

I'll still add composer to the base image, since that's the package manager we're defaulting to for all Drupal stuff anyway.

**Comment by cafuego** [comment]
I had a poke around and baked a composerified image with wp-cli (and a PAGER fix for wp-cli) in https://github.com/UN-OCHA/docker-images/pull/192  See what you reckon.

**Comment by teodorescuserban** [comment]
Will test it but even if it doesnt work, going that way and fix it is preferable.
Closing this one.

**Pull request closed without merging**
