### PR TITLE
[OPS-5712] Configure syslog where it counts, so we get PHP logs in ELK.

### PR DESCRIPTION
**Pull request by cafuego**
After some fiddling on hidblog, it turns out that the settings in php-fpm.conf are ignored (or not passed on) and these settings *must* live under a [syslog] section in a global ini file.

### CODE REVIEW

**Comment by teodorescuserban** [comment]
Looks good. Can't review though :)

**Comment by cafuego** [comment]
Ugggh. Changed from assignees to reviewers. Maybe I am sicker than I thought.

**Review by teodorescuserban — DISMISSED** [review]
⭐️

**Review by orakili — DISMISSED** [review]
Looks good to me, thanks.

**Comment by cafuego** [comment]
Checked the data in ELK, local4 is not as yet used, so I picked that as the default. Documented in https://docs.google.com/document/d/1rLp_dd9GFyYwHk7yhZ-WaJbiz72V-CeJ_HBNXJWmV40/edit#heading=h.bmtld27ue1cf and in the `42-syslog.conf` logstash config file.

**Comment by cafuego** [comment]
Baked a set of PHP images off this.

**Review by orakili — APPROVED** [review]
Looks good to me.

**Pull request merged**
