### PR TITLE
[OPS-7052] look i bring changes.

### PR DESCRIPTION
**Pull request by teodorescuserban**

### CODE REVIEW

**Review by cafuego — CHANGES_REQUESTED** [review]
Keepalived can get in the bin.

**Comment by teodorescuserban** [comment]
In the 🗑️  it goes

**Review by cafuego — DISMISSED** [review]
Good, good. I also pushed some uncommitted changes I had sitting round.

**Review by cafuego — APPROVED** [review]
I welcome our new cleaned up docker image overlords.

**Pull request merged**
