### PR TITLE
[OPS-6072] Add Noto Sans Myanmar as local font. Also make adding new …

### PR DESCRIPTION
**Pull request by cafuego**
…fonts a bit easier in the future; just drop a folder with TTF files under assets/fonts.

### CODE REVIEW

**Comment by cafuego** [comment]
Yep, we don't care that the ci/dockercloud build fails.

**Review by rupl — APPROVED** [review]
I can't figure out how to test this locally so I'll assume you did it flawlessly.

**Comment by rupl** [comment]
If you could, can I please know the exact list of Noto fonts being added once the container is built?

I am having a heck of a time trying to use them in the `unocha/debian-snap-base:10-buster-chrome80-node12-201912-01` image and knowing the exact filenames might give me a clue.

_Edit:_ is this the right list? https://packages.debian.org/sid/all/fonts-noto-core/filelist

**Comment by rupl** [comment]
Ok I managed to get the file list by dumping info out of node:

<details>
<summary><code>fs.readdirSync('/usr/share/fonts/truetype/noto')</code></summary>
<code><pre>
snap_1  | 15:17:52 0|app    | NotoKufiArabic-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoKufiArabic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoMono-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoMusic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoNaskhArabic-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoNaskhArabic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoNaskhArabicUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoNaskhArabicUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoNastaliqUrdu-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoNastaliqUrdu-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSans-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSans-BoldItalic.ttf
snap_1  | 15:17:52 0|app    | NotoSans-Italic.ttf
snap_1  | 15:17:52 0|app    | NotoSans-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansAdlam-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansAdlamUnjoined-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansAnatolianHieroglyphs-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansArabic-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansArabic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansArabicUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansArabicUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansArmenian-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansArmenian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansAvestan-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBamum-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBassaVah-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBatak-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBengali-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansBengali-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBengaliUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansBengaliUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBhaiksuki-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBrahmi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBuginese-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansBuhid-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCanadianAboriginal-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansCanadianAboriginal-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCarian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCaucasianAlbanian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansChakma-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCham-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansCham-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCherokee-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansCherokee-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCoptic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCuneiform-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansCypriot-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansDeseret-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansDevanagari-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansDevanagari-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansDevanagariUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansDevanagariUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansDisplay-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansDisplay-BoldItalic.ttf
snap_1  | 15:17:52 0|app    | NotoSansDisplay-Italic.ttf
snap_1  | 15:17:52 0|app    | NotoSansDisplay-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansDuployan-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansEgyptianHieroglyphs-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansElbasan-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansEthiopic-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansEthiopic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGeorgian-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansGeorgian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGlagolitic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGothic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGrantha-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGujarati-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansGujarati-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGujaratiUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansGujaratiUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGurmukhi-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansGurmukhi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansGurmukhiUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansGurmukhiUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansHanunoo-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansHatran-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansHebrew-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansHebrew-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansImperialAramaic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansInscriptionalPahlavi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansInscriptionalParthian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansJavanese-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKaithi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKannada-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansKannada-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKannadaUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansKannadaUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKayahLi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKharoshthi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKhmer-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansKhmer-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKhmerUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansKhmerUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansKhudawadi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLao-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansLao-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLaoUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansLaoUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLepcha-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLimbu-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLinearA-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLinearB-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLisu-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLycian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansLydian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMahajani-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMalayalam-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansMalayalam-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMalayalamUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansMalayalamUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMandaic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansManichaean-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMarchen-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMeeteiMayek-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMendeKikakui-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMeroitic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMiao-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansModi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMongolian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMono-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansMono-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMro-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMultani-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMyanmar-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansMyanmar-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansMyanmarUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansMyanmarUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansNKo-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansNabataean-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansNewTaiLue-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansNewa-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOgham-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOlChiki-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldHungarian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldItalic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldNorthArabian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldPermic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldPersian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldSouthArabian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOldTurkic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOriya-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansOriya-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOriyaUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansOriyaUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOsage-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansOsmanya-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansPahawhHmong-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansPalmyrene-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansPauCinHau-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansPhagsPa-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansPhoenician-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansPsalterPahlavi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansRejang-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansRunic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSamaritan-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSaurashtra-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSharada-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansShavian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSinhala-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansSinhala-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSinhalaUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansSinhalaUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSoraSompeng-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSundanese-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSylotiNagri-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSymbols-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansSymbols-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSymbols2-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSyriac-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSyriacEastern-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSyriacEstrangela-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansSyriacWestern-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTagalog-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTagbanwa-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTaiLe-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTaiTham-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTaiViet-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTakri-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTamil-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansTamil-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTamilUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansTamilUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTelugu-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansTelugu-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTeluguUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansTeluguUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansThaana-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansThaana-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansThai-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansThai-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansThaiUI-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansThaiUI-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTibetan-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSansTibetan-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTifinagh-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansTirhuta-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansUgaritic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansVai-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansWarangCiti-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSansYi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerif-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerif-BoldItalic.ttf
snap_1  | 15:17:52 0|app    | NotoSerif-Italic.ttf
snap_1  | 15:17:52 0|app    | NotoSerif-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifAhom-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifArmenian-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifArmenian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifBalinese-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifBengali-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifBengali-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifDevanagari-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifDevanagari-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifDisplay-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifDisplay-BoldItalic.ttf
snap_1  | 15:17:52 0|app    | NotoSerifDisplay-Italic.ttf
snap_1  | 15:17:52 0|app    | NotoSerifDisplay-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifEthiopic-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifEthiopic-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifGeorgian-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifGeorgian-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifGujarati-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifGujarati-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifGurmukhi-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifGurmukhi-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifHebrew-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifHebrew-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifKannada-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifKannada-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifKhmer-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifKhmer-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifLao-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifLao-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifMalayalam-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifMalayalam-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifMyanmar-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifMyanmar-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifSinhala-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifSinhala-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTamil-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTamil-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTamilSlanted-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTamilSlanted-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTelugu-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTelugu-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifThai-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifThai-Regular.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTibetan-Bold.ttf
snap_1  | 15:17:52 0|app    | NotoSerifTibetan-Regular.ttf
</pre><code>
</details>

**Comment by cafuego** [comment]
* https://packages.debian.org/buster/fonts-noto-core (names)
* https://packages.debian.org/buster/all/fonts-noto-core/filelist (files)

And the other installed set is https://packages.debian.org/buster/fonts-noto-ui-core

**Pull request closed without merging**
