### PR TITLE
add aws-cli

### PR DESCRIPTION
**Pull request by teodorescuserban**

### CODE REVIEW

**Comment by cafuego** [comment]
What is this one for?

**Comment by teodorescuserban** [comment]
@cafuego, to be used by jenkins to ship snapshots and things (core files for example) from servers directly into the snapshots bucket.
`aws s3 cp srcfile s3://unocha-tools-snapshots/dstfolder/`

**Comment by cafuego** [comment]
I think just use the awscli on the host, don't bother with containerising it.

**Comment by vauxia** [comment]
Confirmed. 

> I think just use the awscli on the host, don't bother with containerising it.

Confirmed. Can we won't-fix?

**Comment by cafuego** [comment]
Yes, I think so.

**Comment by teodorescuserban** [comment]
Erm, the image is up on dockerhub and already in use on some jenkins jobs. 
Using the aws cli dockerized means we can bypass the permissions or fix permissions where the jenkins user wont be able to.

**Pull request merged**
